# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1760972909);
user_pref("app.update.lastUpdateTime.background-update-timer", 1760972669);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1760973029);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1760972429);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1760972789);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1760972549);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1760973149);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 31);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20151221130713");
user_pref("browser.shell.defaultBrowserCheckCount", 2);
user_pref("browser.slowStartup.averageTime", 3021);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20151221130713");
user_pref("browser.startup.homepage_override.mstone", "43.0.2");
user_pref("browser.taskbar.lastgroupid", "308046B0AF4A39CB");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("browser.usedOnWindows10", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1651986093244");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1760972319566");
user_pref("datareporting.policy.firstRunTime", "1651899693244");
user_pref("datareporting.sessions.current.activeTicks", 29);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 738);
user_pref("datareporting.sessions.current.main", 71);
user_pref("datareporting.sessions.current.sessionRestored", 852);
user_pref("datareporting.sessions.current.startTime", "1760972308696");
user_pref("datareporting.sessions.current.totalTime", 1133);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.prunedIndex", 0);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:43.0.2");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "43.0.2");
user_pref("extensions.lastPlatformVersion", "43.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"C:\\\\Program Files\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"43.0.2\",\"st\":1651899682904,\"mt\":1450742673000}}}");
user_pref("gecko.buildID", "20151221130713");
user_pref("gecko.mstone", "43.0.2");
user_pref("gfx.crash-guard.d3d11layers.appVersion", "43.0.2");
user_pref("gfx.crash-guard.d3d11layers.deviceID", "0x5917");
user_pref("gfx.crash-guard.d3d11layers.driverVersion", "31.0.101.2125");
user_pref("gfx.crash-guard.d3d11layers.feature-d2d", true);
user_pref("gfx.crash-guard.d3d11layers.feature-d3d11", true);
user_pref("gfx.crash-guard.status.d3d11layers", 2);
user_pref("gfx.crash-guard.status.d3d9video", 2);
user_pref("gfx.direct3d.last_used_feature_level_idx", 0);
user_pref("idle.lastDailyNotification", 1760973305);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-msvc");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1760972374);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20151221130713");
user_pref("media.gmp-manager.lastCheck", 1760972370);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1760973305);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("sanity-test.device-id", "0x5917");
user_pref("sanity-test.driver-version", "31.0.101.2125");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "43.0.2");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1760973305);
user_pref("toolkit.startup.last_success", 1760972308);
user_pref("toolkit.telemetry.cachedClientID", "5f0ab618-69e3-4d11-aac5-3c3fa07f0706");
user_pref("toolkit.telemetry.previousBuildID", "20151221130713");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Rotation sensor not found.");
